USE Madang;
DROP TABLE SUMMER;

CREATE TABLE SUMMER (
sid int PRIMARY KEY,
calss VARCHAR(20),
PRICE INT
);

INSERT INTO SUMMER VALUES (100, 'FORTRAN', 20000);
INSERT INTO SUMMER VALUES (150, 'PASCAL', 15000);
INSERT INTO SUMMER VALUES (200, 'C', 10000);
INSERT INTO SUMMER VALUES (250, 'FORTRAN', 20000);

SELECT * FROM SUMMER;
